apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow
  MONGO_URI: mongodb://mongo:27017
  MONGO_DB: taskflow
